<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.yospace.iam</groupId>
  <artifactId>yospace-ext-iam-dcp-lib-presentation</artifactId>
  <version>0.0.3-SNAPSHOT</version>
  <name>yospace-extensions-iam-dcp-lib</name>
  <description>yospace-extensions-iam-dcp-lib</description>
  
  <dependencies>
<!--    api(project(":spi:common:decentralized-claims-spi"))-->
      <dependency>
        <groupId>com.yospace.iam</groupId>
        <artifactId>yospace-iam-dcp-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--     api(project(":spi:common:jwt-spi"))   -->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-jwt</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
      
<!--    testImplementation(project(":core:common:junit"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>junit</artifactId>
        <version>0.18.0</version>
      </dependency>        
<!--    testImplementation(testFixtures(project(":spi:common:verifiable-credentials-spi")))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>verifiable-credentials-spi</artifactId>
        <version>0.18.0</version>
      </dependency>    
  </dependencies>  
</project>