<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.youdatax.iam</groupId>
  <artifactId>youdatax-iam-dcp-lib</artifactId>
  <version>0.0.3-SNAPSHOT</version>
  <name>yospace-ext-iam-decentralized-claims-service</name>
  <description>yospace-ext-iam-decentralized-claims-service</description>
  
  <dependencies>
<!--    api(project(":spi:common:decentralized-claims-spi"))-->
      <dependency>
        <groupId>com.yospace.iam</groupId>
        <artifactId>yospace-iam-dcp-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    api(project(":spi:common:identity-did-spi"))-->
       <dependency>
        <groupId>com.yospace.iam</groupId>
        <artifactId>yospace-iam-dcp-did-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>   
<!--    api(project(":spi:common:jwt-spi"))-->
       <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-jwt</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>   
<!--    api(project(":spi:common:token-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-token</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    implementation(project(":core:common:lib:util-lib"))-->
      <dependency>
        <groupId>com.yospace.common</groupId>
        <artifactId>yospace-common-util-lib</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    implementation(libs.nimbus.jwt)
nimbus-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbus" }-->
      <dependency>
        <groupId>com.nimbusds</groupId>
        <artifactId>nimbus-jose-jwt</artifactId>
        <version>10.6</version>
      </dependency>    
<!--    implementation(libs.iron.ed25519)
iron-ed25519 = { module = "com.apicatalog:iron-ed25519-cryptosuite-2020", version.ref = "apicatalog" }-->
      <dependency>
        <groupId>com.apicatalog</groupId>
        <artifactId>iron-ed25519-cryptosuite-2020</artifactId>
        <version>0.14.0</version>
      </dependency>    
      
<!--    testImplementation(testFixtures(project(":spi:common:decentralized-claims-spi")))
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>decentralized-claims-spi</artifactId>
        <version>0.15.1</version>
      </dependency>  -->  
<!--    testImplementation(project(":core:common:junit"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>junit</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    testImplementation(project(":spi:common:json-ld-spi"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>json-ld-spi</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    testImplementation(project(":core:common:lib:json-ld-lib"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>json-ld-lib</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    testImplementation(project(":core:common:lib:crypto-common-lib"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>crypto-common-lib</artifactId>
        <version>0.18.0</version>
      </dependency>
<!--    testImplementation(testFixtures(project(":spi:common:verifiable-credentials-spi")))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>verifiable-credentials-spi</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    testImplementation(testFixtures(project(":extensions:common:crypto:ldp-verifiable-credentials")))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>ldp-verifiable-credentials</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    testImplementation(testFixtures(project(":extensions:common:crypto:jwt-verifiable-credentials")))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>jwt-verifiable-credentials</artifactId>
        <version>0.18.0</version>
      </dependency>
  </dependencies>  
</project>