<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.yospace.core</groupId>
  <artifactId>yospace-ext-iam-dcp-service-issuers-configuration</artifactId>
  <version>0.0.3-SNAPSHOT</version>
  <name>yospace-ext-iam-decentralized-claims-issuers-configuration</name>
  <description>yospace-ext-iam-decentralized-claims-issuers-configuration</description>
  
  <dependencies>
<!--    api(project(":spi:common:decentralized-claims-spi"))-->
      <dependency>
        <groupId>com.yospace.iam</groupId>
        <artifactId>yospace-iam-dcp-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>        
      
<!--    testImplementation(project(":core:common:junit"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>junit</artifactId>
        <version>0.18.0</version>
        <scope>test</scope>
      </dependency>   
 <!--      junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter" }-->
      <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-params</artifactId>
        <version>6.0.1</version>
        <scope>test</scope>
      </dependency>                
  </dependencies>  
</project>