<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.youdatax.iam</groupId>
  <artifactId>youdatax-iam-did-service-web</artifactId>
  <version>0.0.3-SNAPSHOT</version>
  <name>yospace-ext-iam-decentralized-identity-did-web</name>
  <description>yospace-ext-iam-decentralized-identity-did-web</description>
  
  <dependencies>
<!--    api(project(":spi:common:identity-did-spi"))-->
      <dependency>
        <groupId>com.yospace.iam</groupId>
        <artifactId>yospace-iam-dcp-did-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    api(project(":spi:common:http-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-http</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":core:common:lib:util-lib"))-->
      <dependency>
        <groupId>com.yospace.common</groupId>
        <artifactId>yospace-common-util-lib</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
      
<!--    testImplementation(testFixtures(project(":core:common:lib:http-lib")))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>http-lib</artifactId>
        <version>0.18.0</version>
      </dependency>
  </dependencies>  
</project>